import * as vscode from 'vscode';
import { t } from '../l10n';
import { nlsManifestCoverage } from './nls-coverage-data';

/**
 * One-time, per-language notice that the extension's MANIFEST chrome (command titles,
 * settings, menus) is largely English in the editor's current display language.
 *
 * VS Code — not the extension — selects which `package.nls.<locale>.json` ships, so there
 * is no language picker to gate; the honest move is to tell the user the chrome is partial.
 * The runtime log viewer is ~fully localized, so the notice reassures that the main surface
 * is fine. Coverage numbers come from the audited `nls-coverage-data.ts` (regenerated by
 * `npm run generate:nls-coverage`), never a hand-set guess.
 */

/**
 * Below this manifest coverage percent the notice fires. Set high because every shipped
 * non-English manifest is currently 22–37% translated — all of them are substantially
 * English, and a user picking that display language deserves to know once.
 */
const NOTICE_THRESHOLD_PCT = 90;

/** Per-language gate so switching VS Code's display language re-notifies for the new one. */
const noticeShownKeyPrefix = 'slc.nlsCoverageNoticeShown.';

/**
 * Resolve VS Code's display language to a coverage-map key. Tries the full lowercased tag
 * (e.g. `pt-br`, `zh-cn`) first, then the primary subtag (`de` from `de-at`). Returns
 * undefined when no coverage is tracked for the language (English or an unshipped locale).
 */
export function resolveCoverageKey(language: string): string | undefined {
    const tag = language.toLowerCase();
    if (tag in nlsManifestCoverage) { return tag; }
    const [base] = tag.split('-');
    return base in nlsManifestCoverage ? base : undefined;
}

/**
 * Human-readable language name in that language (e.g. `Deutsch`, `日本語`). Falls back to the
 * raw tag if the runtime's Intl data cannot name it — never throws into activation.
 */
function languageDisplayName(language: string): string {
    try {
        const names = new Intl.DisplayNames([language], { type: 'language' });
        return names.of(language) ?? language;
    } catch {
        return language;
    }
}

/**
 * Show the partial-coverage notice at most once per display language. Safe to call on every
 * activation: returns immediately for English, untracked locales, locales above the
 * threshold, or a language already notified. Never throws — activation must not be blocked.
 */
export function maybeNotifyPartialNlsCoverage(context: vscode.ExtensionContext): void {
    const language = vscode.env.language;
    const key = resolveCoverageKey(language);
    if (!key) { return; }

    const coverage = nlsManifestCoverage[key];
    if (coverage >= NOTICE_THRESHOLD_PCT) { return; }

    const shownKey = noticeShownKeyPrefix + key;
    if (context.globalState.get<boolean>(shownKey)) { return; }
    void context.globalState.update(shownKey, true);

    const name = languageDisplayName(language);
    void vscode.window.showInformationMessage(t('msg.nlsPartialCoverage', name, coverage));
}
