// AUTO-GENERATED by scripts/modules/generate/nls-coverage.mjs — do not edit by hand.
// Run `npm run generate:nls-coverage` after changing any package.nls*.json file.
//
// Percent of MANIFEST strings (command titles, settings, menus) actually translated
// per locale, measured as values that differ from the English source. The runtime
// activation notice reads this to honestly tell users when chrome is largely English.
// English is the source and is always 100%.

/** Manifest translation coverage (0-100) keyed by VS Code display-language tag. */
export const nlsManifestCoverage: Readonly<Record<string, number>> = {
    en: 100,
    "de": 34,
    "es": 33,
    "fr": 20,
    "it": 20,
    "ja": 33,
    "ko": 33,
    "pt-br": 20,
    "ru": 20,
    "zh-cn": 33,
    "zh-tw": 20,
};
