/**
 * Bug report variants (plan 052 Group 3).
 *
 * Two compact alternatives to the full 6-part bug report at `report-file-formatter.ts`:
 *
 *   - `formatGitHubIssue` — section ordering and headings match GitHub's default issue template
 *     conventions (Summary / Steps / Expected / Actual / Logs / Environment), so a paste into a
 *     new issue lands in the right slots. Output is significantly shorter than the full report
 *     because each section is scoped to what an outside reader needs, not the full audit trail.
 *
 *   - `formatHandoffBundle` — three-section markdown subset for "I'm stuck, can you look?"
 *     teammate messages. ~30 lines. Skips Full Output, cross-session analysis, environment table,
 *     user-fillable sections — keeps just: what broke, where, what to look at next.
 *
 * Both variants accept the same `ReportFileData` shape the main formatter uses so the
 * upstream data-collection path stays identical.
 */

import type { ReportFileData } from './report-file-formatter';
import { buildItemUrl } from '../marketplace-url';
import { fencedBlock } from '../misc/outbound-content-safety';

const MAX_HANDOFF_FULL_LINES = 12; // Cap raw log lines in handoff so the bundle stays small.
const MAX_GH_FULL_LINES = 80;      // GitHub issues collapse <details> so this can run longer.

/**
 * GitHub-issue preset. Section names + ordering match GitHub's default issue template so paste
 * lands in the right slots. Logs go inside a `<details>` block — GitHub renders this collapsed
 * by default, keeping the issue scannable. The footer link still credits Saropa Log Capture.
 */
export function formatGitHubIssue(data: ReportFileData): string {
    const d = data.bugReportData;
    const url = buildItemUrl('Saropa.saropa-log-capture');
    const sections: string[] = [];

    sections.push('## Summary');
    sections.push(d.errorLine ? `\`${truncate(d.errorLine, 200)}\`` : '*Describe the issue in one or two sentences.*');

    sections.push('## Steps to Reproduce');
    sections.push('1. \n2. \n3. ');

    sections.push('## Expected Behavior');
    sections.push('*What did you expect to happen?*');

    sections.push('## Actual Behavior');
    if (data.selectedText.trim()) {
        sections.push('Selected output:\n\n' + fencedBlock(data.selectedText.trim()));
    } else if (d.errorLine) {
        sections.push(fencedBlock(d.errorLine));
    } else {
        sections.push('*What actually happened?*');
    }

    sections.push('## Logs');
    sections.push(formatLogsBlock(data, MAX_GH_FULL_LINES));

    sections.push('## Environment');
    sections.push(formatEnvTable(data));

    /* Trailing credit + fingerprint so the issue is greppable later. */
    sections.push(`---\n\n_Generated by [Saropa Log Capture](${url}). Error fingerprint: \`${d.fingerprint}\`_`);

    return sections.join('\n\n');
}

/**
 * Compact handoff bundle. Three sections, ~30 lines target. Designed for paste into a Slack/
 * Discord/Teams message where the recipient needs the minimum context to know what's wrong
 * and where to look — not a full audit. Cross-session match and lint info are surfaced when
 * present because they're the load-bearing "what to look at next" signals.
 */
export function formatHandoffBundle(data: ReportFileData): string {
    const d = data.bugReportData;
    const sections: string[] = [];

    sections.push('# Quick handoff');

    sections.push('## What happened');
    if (d.errorLine) {
        sections.push('Error: `' + truncate(d.errorLine, 160) + '`');
    } else if (data.selectedText.trim()) {
        sections.push('Selected output:\n' + fencedBlock(truncate(data.selectedText.trim(), 240)));
    } else {
        sections.push('*No error captured — describe what you saw.*');
    }

    sections.push('## Where');
    const wherePieces: string[] = [];
    if (d.logFilename) {
        const line = d.lineNumber > 0 ? `:${d.lineNumber}` : '';
        wherePieces.push(`Log: \`${d.logFilename}${line}\``);
    }
    if (d.environment && d.environment['Project']) {
        wherePieces.push(`Project: \`${d.environment['Project']}\``);
    }
    if (d.devEnvironment && d.devEnvironment['Git Branch']) {
        wherePieces.push(`Branch: \`${d.devEnvironment['Git Branch']}\``);
    }
    sections.push(wherePieces.length > 0 ? wherePieces.join(' · ') : '*Location not captured.*');

    sections.push('## What to look at next');
    const hints: string[] = [];
    if (d.crossSessionMatch) {
        /* Cross-session match is the highest-signal hint — "this isn't the first time" tells the
           reader they're not in fresh-investigation territory. */
        hints.push(`- Cross-session match: this error has appeared before (fingerprint \`${d.fingerprint}\`).`);
    } else {
        hints.push('- First occurrence: no cross-session match for this fingerprint.');
    }
    if (d.lintMatches?.matches.length) {
        hints.push(`- Lint context: ${d.lintMatches.matches.length} active diagnostic(s) on the implicated file.`);
    }
    if (data.fullOutput.trim()) {
        hints.push(`- Last ${MAX_HANDOFF_FULL_LINES} log lines below.`);
    }
    sections.push(hints.join('\n'));

    if (data.fullOutput.trim()) {
        const tail = takeLastLines(data.fullOutput, MAX_HANDOFF_FULL_LINES);
        sections.push(fencedBlock(tail));
    }

    return sections.join('\n\n');
}

function formatLogsBlock(data: ReportFileData, maxLines: number): string {
    if (!data.fullOutput.trim()) {
        return '*No output captured.*';
    }
    const lines = data.fullOutput.split('\n');
    const truncated = lines.length > maxLines;
    const slice = truncated ? lines.slice(-maxLines).join('\n') : data.fullOutput;
    const summary = truncated ? `Last ${maxLines} of ${lines.length} lines` : `${lines.length} lines`;
    return `<details><summary>${summary}</summary>\n\n${fencedBlock(slice)}\n\n</details>`;
}

function formatEnvTable(data: ReportFileData): string {
    const rows = [
        `| Extension | ${data.extensionVersion} |`,
        `| VS Code | ${data.vsCodeVersion} |`,
        `| OS | ${data.os} |`,
    ];
    const adapter = data.bugReportData.environment['Debug Adapter'] ?? data.sessionInfo['Debug Adapter'];
    if (adapter) { rows.push(`| Debug Adapter | ${adapter} |`); }
    return '| Field | Value |\n|-------|-------|\n' + rows.join('\n');
}

function truncate(text: string, max: number): string {
    if (text.length <= max) { return text; }
    return text.slice(0, max - 1) + '…';
}

function takeLastLines(text: string, n: number): string {
    const lines = text.split('\n');
    return lines.slice(-n).join('\n');
}
