/**
 * Markdown formatter for auto-created bug report files.
 *
 * Assembles a 6-part report: selected text, session info, full output,
 * cross-session analysis, environment, and user-fillable sections.
 */

import type { BugReportData } from './bug-report-collector';
import { buildItemUrl } from '../marketplace-url';
import {
    formatCrossSession, formatProductionImpact, formatFooter,
} from './bug-report-sections';

/** All data needed to format a report file. */
export interface ReportFileData {
    readonly selectedText: string;
    readonly selectedLineStart: number;
    readonly selectedLineEnd: number;
    readonly sessionInfo: Record<string, string>;
    readonly fullOutput: string;
    readonly fullOutputLineCount: number;
    readonly bugReportData: BugReportData;
    readonly extensionVersion: string;
    readonly vsCodeVersion: string;
    readonly os: string;
}

/** Format a complete bug report file from collected data. */
export function formatReportFile(data: ReportFileData): string {
    const sections = [
        formatHeader(),
        formatSelectedText(data),
        formatSessionInfo(data),
        formatFullOutput(data),
        formatAnalysis(data),
        formatEnvSection(data),
        formatUserSections(),
        formatFooter(data.bugReportData.logFilename, data.bugReportData.lineNumber),
    ];
    return sections.join('\n\n');
}

function formatHeader(): string {
    const url = buildItemUrl('Saropa.saropa-log-capture');
    return [
        '# Saropa Log Capture — Bug Report',
        `**Generated by [Saropa Log Capture](${url})** | ${new Date().toISOString()}`,
    ].join('\n\n');
}

function formatSelectedText(data: ReportFileData): string {
    if (!data.selectedText.trim()) {
        return '## Part 1: Selected Text\n\n*No text selected.*';
    }
    const range = data.selectedLineStart === data.selectedLineEnd
        ? `line ${data.selectedLineStart}`
        : `lines ${data.selectedLineStart}–${data.selectedLineEnd}`;
    return [
        '## Part 1: Selected Text',
        `> ${range} in \`${data.bugReportData.logFilename}\``,
        `\`\`\`\n${data.selectedText}\n\`\`\``,
    ].join('\n\n');
}

function formatSessionInfo(data: ReportFileData): string {
    const env = { ...data.sessionInfo, ...data.bugReportData.environment };
    const keys = Object.keys(env);
    if (keys.length === 0) {
        return '## Part 2: Session Information\n\n*No session information available.*';
    }
    const rows = keys.map(k => `| ${k} | ${env[k].replace(/\|/g, '\\|')} |`);
    return [
        '## Part 2: Session Information',
        '| Field | Value |\n|-------|-------|\n' + rows.join('\n'),
    ].join('\n\n');
}

function formatFullOutput(data: ReportFileData): string {
    if (!data.fullOutput.trim()) {
        return '## Part 3: Full Session Output\n\n*No output captured.*';
    }
    const count = data.fullOutputLineCount || data.fullOutput.split('\n').length;
    return [
        '## Part 3: Full Session Output',
        `<details><summary>Full output (${count} lines, decorated)</summary>`,
        '',
        '```',
        data.fullOutput,
        '```',
        '',
        '</details>',
    ].join('\n');
}

function formatAnalysis(data: ReportFileData): string {
    const parts: string[] = ['## Part 4: Cross-Session Analysis'];
    const d = data.bugReportData;
    parts.push(`**Error fingerprint:** \`${d.fingerprint}\``);
    if (d.crossSessionMatch) {
        parts.push(formatCrossSession(d.crossSessionMatch));
    } else {
        parts.push('*First occurrence — no cross-session matches found.*');
    }
    if (d.collectionContext) {
        parts.push(formatCollectionBrief(d.collectionContext));
    }
    if (d.firebaseMatch) {
        parts.push(formatProductionImpact(d.firebaseMatch));
    }
    return parts.join('\n\n');
}

function formatCollectionBrief(inv: BugReportData['collectionContext']): string {
    if (!inv) { return ''; }
    return [
        `### Active Collection: ${inv.name}`,
        `- Sources: ${inv.sources.length}`,
        inv.lastSearchQuery ? `- Last search: \`${inv.lastSearchQuery}\`` : '',
        inv.notes?.trim() ? `- Notes: ${inv.notes.trim()}` : '',
    ].filter(Boolean).join('\n');
}

function formatEnvSection(data: ReportFileData): string {
    const rows = [
        `| Extension | ${data.extensionVersion} |`,
        `| VS Code | ${data.vsCodeVersion} |`,
        `| OS | ${data.os} |`,
    ];
    const adapter = data.bugReportData.environment['Debug Adapter']
        ?? data.sessionInfo['Debug Adapter'];
    if (adapter) { rows.push(`| Debug Adapter | ${adapter} |`); }
    const workspace = data.sessionInfo['Project']
        ?? data.bugReportData.environment['Project'];
    if (workspace) { rows.push(`| Workspace | ${workspace} |`); }
    return [
        '## Part 5: Environment',
        '| Field | Value |\n|-------|-------|\n' + rows.join('\n'),
    ].join('\n\n');
}

function formatUserSections(): string {
    return [
        '## Part 6: User Notes',
        '### Steps to Reproduce',
        '1. \n2. \n3. ',
        '### Expected Behavior',
        '',
        '### Actual Behavior',
        '',
        '### Severity',
        '- [ ] Critical\n- [ ] Major\n- [ ] Minor\n- [ ] Cosmetic',
    ].join('\n\n');
}
