/**
 * Bug report markdown formatter.
 *
 * Formats collected BugReportData into a structured markdown string
 * suitable for pasting into GitHub Issues, StackOverflow, or Slack.
 */

import type { BugReportData, StackFrame, CrossSessionMatch } from './bug-report-collector';
import type { BlameLine } from './git-blame';
import type { SourceCodePreview, GitCommit } from './workspace-analyzer';
import type { DocScanResults } from './docs-scanner';
import type { ImportResults } from './import-extractor';
import type { SymbolResults } from './symbol-resolver';
import { type SectionData, scoreRelevance } from './analysis-relevance';
import { extractDateFromFilename } from './stack-parser';

/** Format collected data into a complete markdown bug report. */
export function formatBugReport(data: BugReportData): string {
    const summary = formatExecutiveSummary(data);
    const sections = [
        formatHeader(),
        ...(summary ? [summary] : []),
        formatError(data.errorLine, data.fingerprint),
        formatStackTrace(data.stackTrace),
        formatLogContext(data.logContext),
        formatEnvironment(data.environment),
        formatDevEnvSection(data.devEnvironment),
    ];
    if (data.sourcePreview) { sections.push(formatSourceCode(data.sourcePreview)); }
    if (data.blame) { sections.push(formatBlame(data.blame)); }
    if (data.gitHistory.length > 0) { sections.push(formatGitHistory(data.gitHistory)); }
    if (data.lineRangeHistory.length > 0) { sections.push(formatLineRangeHistory(data.lineRangeHistory)); }
    if (data.imports) { sections.push(formatImports(data.imports)); }
    if (data.docMatches?.matches.length) { sections.push(formatDocMatches(data.docMatches)); }
    if (data.resolvedSymbols?.symbols.length) { sections.push(formatSymbolDefs(data.resolvedSymbols)); }
    if (data.crossSessionMatch) { sections.push(formatCrossSession(data.crossSessionMatch)); }
    sections.push(formatFooter(data.logFilename, data.lineNumber));
    return sections.join('\n\n');
}

function formatHeader(): string {
    return `# Bug Report\n\n**Generated by Saropa Log Capture** | ${new Date().toISOString()}`;
}

function formatError(errorLine: string, fingerprint: string): string {
    return `## Error\n\n\`\`\`\n${errorLine}\n\`\`\`\n\n**Fingerprint:** \`${fingerprint}\``;
}

function formatStackTrace(frames: readonly StackFrame[]): string {
    if (frames.length === 0) { return '## Stack Trace\n\n*No stack trace detected.*'; }
    const appCount = frames.filter(f => f.isApp).length;
    const fwCount = frames.length - appCount;
    const lines = frames.map(f => f.isApp ? `>>> ${f.text}` : `    ${f.text}`);
    return [
        '## Stack Trace',
        `\`\`\`\n${lines.join('\n')}\n\`\`\``,
        `${frames.length} frames (${appCount} app, ${fwCount} framework) — \`>>>\` marks app code`,
    ].join('\n\n');
}

function formatLogContext(context: readonly string[]): string {
    if (context.length === 0) { return '## Log Context\n\n*No preceding log lines.*'; }
    const block = context.map(l => l.trimEnd()).join('\n');
    return `## Log Context (${context.length} lines before error)\n\n\`\`\`\n${block}\n\`\`\``;
}

function formatEnvironment(env: Record<string, string>): string {
    const keys = Object.keys(env);
    if (keys.length === 0) { return '## Environment\n\n*No environment data available.*'; }
    const rows = keys.map(k => `| ${k} | ${env[k]} |`);
    return `## Environment\n\n| Field | Value |\n|-------|-------|\n${rows.join('\n')}`;
}

function formatDevEnvSection(env: Record<string, string>): string {
    const keys = Object.keys(env);
    if (keys.length === 0) { return '## Development Environment\n\n*No dev environment data available.*'; }
    const rows = keys.map(k => `| ${k} | ${env[k]} |`);
    return `## Development Environment\n\n| Field | Value |\n|-------|-------|\n${rows.join('\n')}`;
}

function formatSourceCode(preview: SourceCodePreview): string {
    const lines = preview.lines.map(l => {
        const marker = l.num === preview.targetLine ? '-->' : '   ';
        return `${marker} ${String(l.num).padStart(4)} | ${l.text}`;
    });
    return `## Source Code\n\n\`\`\`\n${lines.join('\n')}\n\`\`\``;
}

function formatBlame(blame: BlameLine): string {
    return `## Git Blame\n\nLast changed by **${blame.author}** on ${blame.date} · \`${blame.hash}\` ${blame.message}`;
}

function formatGitHistory(commits: readonly GitCommit[]): string {
    return formatCommitTable('## Recent Git History', commits);
}

function formatCrossSession(match: CrossSessionMatch): string {
    const sessions = match.sessionCount === 1 ? '1 session' : `${match.sessionCount} sessions`;
    const total = match.totalOccurrences === 1 ? '1 occurrence' : `${match.totalOccurrences} occurrences`;
    return [
        '## Cross-Session History',
        `This error has been seen in **${sessions}** with **${total}**.`,
        `- First seen: ${match.firstSeen}`,
        `- Last seen: ${match.lastSeen}`,
    ].join('\n');
}

function formatLineRangeHistory(commits: readonly GitCommit[]): string {
    return formatCommitTable('## Recent Changes Near Error', commits);
}

function formatCommitTable(heading: string, commits: readonly GitCommit[]): string {
    const rows = commits.map(c => `| \`${c.hash}\` | ${c.date} | ${escapePipe(c.message)} |`);
    return [heading, '| Hash | Date | Message |\n|------|------|---------|\n' + rows.join('\n')].join('\n\n');
}

function formatImports(results: ImportResults): string {
    if (results.imports.length === 0) { return '## Dependencies\n\n*No imports detected.*'; }
    const local = results.imports.filter(i => i.isLocal).map(i => `- \`${i.module}\` (L${i.line})`);
    const pkg = results.imports.filter(i => !i.isLocal).map(i => `- \`${i.module}\` (L${i.line})`);
    let md = `## Dependencies (${results.language})\n\n`;
    if (local.length > 0) { md += `**Local** (${local.length}):\n${local.join('\n')}\n\n`; }
    if (pkg.length > 0) { md += `**Packages** (${pkg.length}):\n${pkg.join('\n')}`; }
    return md.trimEnd();
}

function formatDocMatches(results: DocScanResults): string {
    const rows = results.matches.map(m => `| ${m.filename}:${m.lineNumber} | ${escapePipe(m.matchedToken)} | ${escapePipe(m.lineText.trim().slice(0, 80))} |`);
    return [
        `## Related Documentation (${results.matches.length} references)`,
        '| Location | Token | Context |\n|----------|-------|---------|\n' + rows.join('\n'),
    ].join('\n\n');
}

function formatSymbolDefs(results: SymbolResults): string {
    const rows = results.symbols.map(s => {
        const file = s.uri.fsPath.split(/[\\/]/).pop() ?? '';
        return `| ${s.kind} | ${escapePipe(s.name)} | ${file}:${s.line} | ${escapePipe(s.containerName)} |`;
    });
    return [
        '## Symbol Definitions',
        '| Kind | Name | Location | Container |\n|------|------|----------|-----------|\n' + rows.join('\n'),
    ].join('\n\n');
}

function formatExecutiveSummary(data: BugReportData): string | undefined {
    const sectionData = extractSectionData(data);
    const { findings } = scoreRelevance(sectionData);
    const bullets = findings.filter(f => f.text && (f.level === 'high' || f.level === 'medium'));
    if (bullets.length === 0) { return undefined; }
    const lines = bullets.map(f => `- ${f.icon} ${f.text}`);
    return `## Key Findings\n\n${lines.join('\n')}`;
}

function extractSectionData(data: BugReportData): SectionData {
    return {
        blame: data.blame ? { date: data.blame.date, author: data.blame.author, hash: data.blame.hash } : undefined,
        lineCommits: data.lineRangeHistory.map(c => ({ date: c.date })),
        annotations: [],
        crossSession: data.crossSessionMatch ? { sessionCount: data.crossSessionMatch.sessionCount, totalOccurrences: data.crossSessionMatch.totalOccurrences, firstSeenDate: extractDateFromFilename(data.crossSessionMatch.firstSeen) } : undefined,
        docMatchCount: data.docMatches?.matches.length ?? 0,
        symbolCount: data.resolvedSymbols?.symbols.length ?? 0,
        tokenMatchCount: 0,
        tokenFileCount: 0,
        importCount: data.imports?.imports.length ?? 0,
        localImportCount: data.imports?.localCount ?? 0,
        gitCommitCount: data.gitHistory.length,
    };
}

function escapePipe(text: string): string { return text.replace(/\|/g, '\\|'); }

function formatFooter(filename: string, lineNumber: number): string {
    return `---\n*Report generated from \`${filename}\` at line ${lineNumber}*`;
}
