import * as assert from 'node:assert';
import {
	mdEscape,
	buildMarkdownHeader,
	buildQuickExportFilename,
	type QuickExportMetadata,
} from '../../ui/provider/viewer-quick-export';

/** Factory for test metadata with sensible defaults. */
function makeMeta(overrides: Partial<QuickExportMetadata> = {}): QuickExportMetadata {
	return {
		sourceFile: '20260330_143022_drift.log',
		totalLines: 10000,
		visibleLines: 500,
		enabledLevels: ['error', 'warning', 'info'],
		appOnly: false,
		exclusionsActive: false,
		searchTerm: '',
		levelCounts: { error: 10, warning: 40, info: 450 },
		...overrides,
	};
}

suite('QuickExport', () => {

	suite('mdEscape', () => {
		test('should return plain text unchanged', () => {
			assert.strictEqual(mdEscape('hello world'), 'hello world');
		});

		test('should escape pipe characters', () => {
			assert.strictEqual(mdEscape('a|b|c'), 'a\\|b\\|c');
		});

		test('should escape backtick characters', () => {
			assert.strictEqual(mdEscape('`code`'), '\\`code\\`');
		});

		test('should escape both pipe and backtick', () => {
			assert.strictEqual(mdEscape('a|`b`'), 'a\\|\\`b\\`');
		});

		test('should handle empty string', () => {
			assert.strictEqual(mdEscape(''), '');
		});
	});

	suite('buildQuickExportFilename', () => {
		const date = new Date(2026, 2, 30, 14, 30, 22); // 2026-03-30 14:30:22

		test('should produce YYYYMMDD_HHMMSS_name_export.md format', () => {
			const result = buildQuickExportFilename('drift-adviser', date);
			assert.strictEqual(result, '20260330_143022_drift-adviser_export.md');
		});

		test('should sanitize unsafe characters in project name', () => {
			const result = buildQuickExportFilename('My Project (v2)', date);
			assert.strictEqual(result, '20260330_143022_My_Project__v2__export.md');
		});

		test('should handle empty project name', () => {
			const result = buildQuickExportFilename('', date);
			assert.strictEqual(result, '20260330_143022__export.md');
		});

		test('should pad single-digit month/day/time components', () => {
			const jan1 = new Date(2026, 0, 5, 3, 7, 9); // 2026-01-05 03:07:09
			const result = buildQuickExportFilename('app', jan1);
			assert.strictEqual(result, '20260105_030709_app_export.md');
		});
	});

	suite('buildMarkdownHeader', () => {
		const date = new Date('2026-03-30T14:30:22.000Z');

		test('should include project name in title', () => {
			const header = buildMarkdownHeader(makeMeta(), 'drift-adviser', date);
			assert.ok(header.startsWith('# Log Export — drift-adviser'));
		});

		test('should contain markdown table with metadata fields', () => {
			const header = buildMarkdownHeader(makeMeta(), 'drift-adviser', date);
			assert.ok(header.includes('| Generated by | Saropa Log Capture |'));
			assert.ok(header.includes('| Project | drift-adviser |'));
			assert.ok(header.includes('| Source file |'));
			assert.ok(header.includes('| Visible lines |'));
			assert.ok(header.includes('| Levels shown |'));
		});

		test('should include level breakdown when counts present', () => {
			const header = buildMarkdownHeader(makeMeta(), 'test', date);
			assert.ok(header.includes('| Breakdown |'));
			assert.ok(header.includes('error: 10'));
			assert.ok(header.includes('info: 450'));
		});

		test('should include app-only row when enabled', () => {
			const header = buildMarkdownHeader(makeMeta({ appOnly: true }), 'test', date);
			assert.ok(header.includes('| App only | yes |'));
		});

		test('should omit app-only row when disabled', () => {
			const header = buildMarkdownHeader(makeMeta({ appOnly: false }), 'test', date);
			assert.ok(!header.includes('App only'));
		});

		test('should include exclusions row when active', () => {
			const header = buildMarkdownHeader(makeMeta({ exclusionsActive: true }), 'test', date);
			assert.ok(header.includes('| Exclusions | active |'));
		});

		test('should include search term when present', () => {
			const header = buildMarkdownHeader(makeMeta({ searchTerm: 'NullPointer' }), 'test', date);
			assert.ok(header.includes('| Search | `NullPointer` |'));
		});

		test('should omit search row when empty', () => {
			const header = buildMarkdownHeader(makeMeta({ searchTerm: '' }), 'test', date);
			assert.ok(!header.includes('| Search'));
		});

		test('should escape pipe chars in project name', () => {
			const header = buildMarkdownHeader(makeMeta(), 'pipe|project', date);
			assert.ok(header.includes('pipe\\|project'));
			assert.ok(!header.includes('| pipe|project |'));
		});

		test('should end with code fence opener', () => {
			const header = buildMarkdownHeader(makeMeta(), 'test', date);
			assert.ok(header.endsWith('```log'));
		});

		test('should show "all" when no levels specified', () => {
			const header = buildMarkdownHeader(makeMeta({ enabledLevels: [] }), 'test', date);
			assert.ok(header.includes('| Levels shown | all |'));
		});
	});
});
