/**
 * Quick-export handler: saves the current viewer state as a markdown report
 * to the configured reports (log) directory with a timestamped filename.
 */

import * as vscode from "vscode";
import { t } from "../../l10n";
import { getConfig, getLogDirectoryUri } from "../../modules/config/config";
import { logExtensionError } from "../../modules/misc/extension-logger";

/** Metadata sent from the webview alongside the visible lines. */
export interface QuickExportMetadata {
	readonly sourceFile: string;
	readonly totalLines: number;
	readonly visibleLines: number;
	readonly enabledLevels: string[];
	readonly appOnly: boolean;
	readonly exclusionsActive: boolean;
	readonly searchTerm: string;
	readonly levelCounts: Record<string, number>;
}

/** Escape pipe and backtick characters for safe markdown table cell values. */
export function mdEscape(s: string): string {
	return s.replace(/\|/g, "\\|").replace(/`/g, "\\`");
}

/** Build the markdown header block for a quick-export report. */
export function buildMarkdownHeader(meta: QuickExportMetadata, projectName: string, now: Date): string {
	const lines: string[] = [
		`# Log Export — ${mdEscape(projectName)}`,
		"",
		"| Field | Value |",
		"| ----- | ----- |",
		`| Generated by | Saropa Log Capture |`,
		`| Date | ${now.toISOString()} |`,
		`| Project | ${mdEscape(projectName)} |`,
		`| Source file | \`${mdEscape(meta.sourceFile)}\` |`,
		`| Visible lines | ${meta.visibleLines.toLocaleString()} of ${meta.totalLines.toLocaleString()} |`,
		`| Levels shown | ${meta.enabledLevels.join(", ") || "all"} |`,
	];

	if (meta.appOnly) { lines.push("| App only | yes |"); }
	if (meta.exclusionsActive) { lines.push("| Exclusions | active |"); }
	if (meta.searchTerm) { lines.push(`| Search | \`${mdEscape(meta.searchTerm)}\` |`); }

	// Level breakdown
	const counts = Object.entries(meta.levelCounts)
		.filter(([, n]) => n > 0)
		.map(([lvl, n]) => `${lvl}: ${n}`)
		.join(", ");
	if (counts) { lines.push(`| Breakdown | ${counts} |`); }

	lines.push("", "---", "", "```log");
	return lines.join("\n");
}

/** Generate a timestamped filename for the quick export. */
export function buildQuickExportFilename(projectName: string, now: Date): string {
	const y = now.getFullYear();
	const mo = String(now.getMonth() + 1).padStart(2, "0");
	const d = String(now.getDate()).padStart(2, "0");
	const h = String(now.getHours()).padStart(2, "0");
	const mi = String(now.getMinutes()).padStart(2, "0");
	const s = String(now.getSeconds()).padStart(2, "0");
	const safe = projectName.replace(/[^a-zA-Z0-9_-]/g, "_");
	return `${y}${mo}${d}_${h}${mi}${s}_${safe}_export.md`;
}

/**
 * Handle a quick-export request from the webview.
 * Writes a markdown report to the configured log directory.
 */
export async function handleQuickExportLogs(
	lines: string[],
	metadata: QuickExportMetadata,
): Promise<void> {
	const wsFolder = vscode.workspace.workspaceFolders?.[0];
	const projectName = wsFolder?.name ?? "project";
	const logDirUri = getLogDirectoryUri(wsFolder);

	// Ensure the directory exists
	try {
		await vscode.workspace.fs.createDirectory(logDirUri);
	} catch {
		// Directory may already exist — that's fine
	}

	const now = new Date();
	const filename = buildQuickExportFilename(projectName, now);
	const fileUri = vscode.Uri.joinPath(logDirUri, filename);

	const header = buildMarkdownHeader(metadata, projectName, now);
	const footer = "\n```\n";
	const content = header + "\n" + lines.join("\n") + footer;

	try {
		await vscode.workspace.fs.writeFile(fileUri, Buffer.from(content, "utf-8"));
		const config = getConfig();
		vscode.window.showInformationMessage(
			t("msg.exportedLinesTo",
				String(metadata.visibleLines),
				metadata.visibleLines === 1 ? "" : "s",
				"",
				`${config.logDirectory}/${filename}`),
		);
	} catch (err) {
		const message = err instanceof Error ? err.message : String(err);
		logExtensionError("quickExportLogs", err instanceof Error ? err : new Error(message));
		throw new Error(`Quick export failed: ${message}`);
	}
}
