/**
 * Quick-export handler: saves the current viewer state as a markdown report
 * to the configured reports (log) directory with a timestamped filename.
 */

import * as vscode from "vscode";
import { t } from "../../l10n";
import { getConfig, getLogDirectoryUri } from "../../modules/config/config";
import { logExtensionError } from "../../modules/misc/extension-logger";

/** Metadata sent from the webview alongside the visible lines. */
export interface QuickExportMetadata {
	readonly sourceFile: string;
	readonly totalLines: number;
	readonly visibleLines: number;
	readonly enabledLevels: string[];
	readonly appOnly: boolean;
	readonly exclusionsActive: boolean;
	readonly searchTerm: string;
	readonly levelCounts: Record<string, number>;
}

/**
 * Escape a value for safe embedding in a markdown table cell.
 * Order matters: backslash MUST be escaped first, or the backslashes this
 * function inserts for `|`/`` ` `` would themselves get re-escaped (or, if a
 * different order let a raw backslash survive next to an inserted escape
 * character, an attacker-controlled value could forge a fake `\|`/`` \` ``
 * escape sequence and break back out of the cell). Newlines are also
 * flattened to spaces since a bare newline would terminate the table row.
 */
export function mdEscape(s: string): string {
	return s
		.replace(/\\/g, "\\\\")
		.replace(/\|/g, "\\|")
		.replace(/`/g, "\\`")
		.replace(/\r\n|\r|\n/g, " ");
}

/**
 * Wrap a value as a literal markdown inline code span (backtick-fenced table
 * cell content). Code spans are verbatim in CommonMark/GFM — backslash
 * escapes are NOT processed inside them, and `|`/`` ` `` already can't break
 * out of a table cell from inside one — so `mdEscape` must never be applied
 * to text destined for a code span, or its inserted backslashes render
 * literally. Instead the fence itself is widened past the longest run of
 * backticks in the value (the standard CommonMark technique), and a single
 * space is added on each side if the value starts/ends with a backtick or is
 * empty, so the fence can't merge with the content.
 */
export function mdCodeSpan(s: string): string {
	const flat = s.replace(/\r\n|\r|\n/g, " ");
	const longestBacktickRun = Math.max(0, ...(flat.match(/`+/g) ?? []).map(run => run.length));
	const fence = "`".repeat(longestBacktickRun + 1);
	const needsPadding = flat === "" || flat.startsWith("`") || flat.endsWith("`");
	return `${fence}${needsPadding ? ` ${flat} ` : flat}${fence}`;
}

/** Build the markdown header block for a quick-export report. */
export function buildMarkdownHeader(meta: QuickExportMetadata, projectName: string, now: Date): string {
	const lines: string[] = [
		`# Log Export — ${mdEscape(projectName)}`,
		"",
		"| Field | Value |",
		"| ----- | ----- |",
		`| Generated by | Saropa Log Capture |`,
		`| Date | ${now.toISOString()} |`,
		`| Project | ${mdEscape(projectName)} |`,
		`| Source file | ${mdCodeSpan(meta.sourceFile)} |`,
		`| Visible lines | ${meta.visibleLines.toLocaleString()} of ${meta.totalLines.toLocaleString()} |`,
		`| Levels shown | ${meta.enabledLevels.join(", ") || "all"} |`,
	];

	if (meta.appOnly) { lines.push("| App only | yes |"); }
	if (meta.exclusionsActive) { lines.push("| Exclusions | active |"); }
	if (meta.searchTerm) { lines.push(`| Search | ${mdCodeSpan(meta.searchTerm)} |`); }

	// Level breakdown
	const counts = Object.entries(meta.levelCounts)
		.filter(([, n]) => n > 0)
		.map(([lvl, n]) => `${lvl}: ${n}`)
		.join(", ");
	if (counts) { lines.push(`| Breakdown | ${counts} |`); }

	lines.push("", "---", "", "```log");
	return lines.join("\n");
}

/** Generate a timestamped filename for the quick export. */
export function buildQuickExportFilename(projectName: string, now: Date): string {
	const y = now.getFullYear();
	const mo = String(now.getMonth() + 1).padStart(2, "0");
	const d = String(now.getDate()).padStart(2, "0");
	const h = String(now.getHours()).padStart(2, "0");
	const mi = String(now.getMinutes()).padStart(2, "0");
	const s = String(now.getSeconds()).padStart(2, "0");
	const safe = projectName.replace(/[^a-zA-Z0-9_-]/g, "_");
	return `${y}${mo}${d}_${h}${mi}${s}_${safe}_export.md`;
}

/**
 * Handle a quick-export request from the webview.
 * Writes a markdown report to the configured log directory.
 */
export async function handleQuickExportLogs(
	lines: string[],
	metadata: QuickExportMetadata,
): Promise<void> {
	const wsFolder = vscode.workspace.workspaceFolders?.[0];
	const projectName = wsFolder?.name ?? "project";
	const logDirUri = getLogDirectoryUri(wsFolder);

	// Ensure the directory exists
	try {
		await vscode.workspace.fs.createDirectory(logDirUri);
	} catch {
		// Directory may already exist — that's fine
	}

	const now = new Date();
	const filename = buildQuickExportFilename(projectName, now);
	const fileUri = vscode.Uri.joinPath(logDirUri, filename);

	const header = buildMarkdownHeader(metadata, projectName, now);
	const footer = "\n```\n";
	const content = header + "\n" + lines.join("\n") + footer;

	try {
		await vscode.workspace.fs.writeFile(fileUri, Buffer.from(content, "utf-8"));
		const config = getConfig();
		vscode.window.showInformationMessage(
			metadata.visibleLines === 1
				? t("msg.exportedLinesTo.one", String(metadata.visibleLines), "", `${config.logDirectory}/${filename}`)
				: t("msg.exportedLinesTo.many", String(metadata.visibleLines), "", `${config.logDirectory}/${filename}`),
		);
	} catch (err) {
		const message = err instanceof Error ? err.message : String(err);
		logExtensionError("quickExportLogs", err instanceof Error ? err : new Error(message));
		throw new Error(`Quick export failed: ${message}`);
	}
}
