/**
 * Before: no committed index of webview → extension `postMessage` types.
 * After: `doc/internal/webview-incoming-message-types.md` is generated by
 * `scripts/modules/webview-message-catalog.mjs` and verified on `npm run compile`.
 */
import * as assert from "node:assert";
import * as fs from "node:fs";
import * as path from "node:path";

function repoRoot(): string {
    return path.resolve(__dirname, "..", "..", "..", "..");
}

suite("webview incoming message catalog (generated doc)", () => {
    test("committed catalog lists dispatcher types and bool-toggle keys", () => {
        const catalogPath = path.join(repoRoot(), "doc", "internal", "webview-incoming-message-types.md");
        assert.ok(fs.existsSync(catalogPath), "catalog markdown must exist at doc/internal/webview-incoming-message-types.md");
        const text = fs.readFileSync(catalogPath, "utf8");
        assert.ok(text.includes("AUTO-GENERATED"), "catalog should be marked auto-generated");
        assert.ok(text.includes("`trackInteraction`"), "root dispatch-only type trackInteraction");
        assert.ok(text.includes("`copyToClipboard`"), "action handler type copyToClipboard");
        assert.ok(text.includes("`setMinimapSqlDensity`"), "bool map toggle type setMinimapSqlDensity");
        assert.ok(text.includes("**Total:**") && /\d+\s+distinct types/.test(text), "catalog should end with a Total count line");
    });

    test("package.json pins Node for contributors", () => {
        const pkgPath = path.join(repoRoot(), "package.json");
        const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8")) as { engines?: { node?: string } };
        assert.ok(pkg.engines?.node, "engines.node should be set");
        assert.match(pkg.engines.node, /22/, "engines.node should reference Node 22");
    });
});
