/**
 * Before: no committed index of extension → webview `postMessage` types.
 * After: `doc/internal/webview-outbound-message-types.md` is generated by
 * `scripts/modules/webview-host-outbound-catalog.mjs` and verified on `npm run compile`.
 */
import * as assert from "node:assert";
import * as fs from "node:fs";
import * as path from "node:path";

function repoRoot(): string {
    return path.resolve(__dirname, "..", "..", "..", "..");
}

suite("webview outbound message catalog (generated doc)", () => {
    test("committed outbound catalog is present and auto-generated", () => {
        const p = path.join(repoRoot(), "doc", "internal", "webview-outbound-message-types.md");
        assert.ok(fs.existsSync(p));
        const text = fs.readFileSync(p, "utf8");
        assert.ok(text.includes("AUTO-GENERATED"), "banner");
        assert.ok(text.includes("`clear`"), "provider posts clear");
        assert.ok(text.includes("**Total:**") && /\d+\s+distinct types/.test(text), "total line");
    });
});
